#cloud-config
users:
  - name: "core"
    groups:
      - "sudo"
      - "docker"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK+XS7PqxDd2OCBGJBNWJ2oFtSYs7fjQh2W9CABnXFMSJWyVpy3SQaEcEq7ptt07i8ESQr/SUZ5xJNhQARgLvRSmB5VIZ+iJ6NEipCkLoJXj7gCJUlswP/crA1hDV2gfwtga1PbgDormt+62r8XYCF0S00yX/iiE2Z4Hx4ZTSPD5VWgwooIsQHUSOeHaPLslMakB9Bg2B4W9ZM5/Gx2xlx5u1x37O6sG9pI2XzP+ZLU+FN24qki2HbtYn7eVDWrkRbPlh0WRintlteytMDKU0iCxPCckB8LpYJAmDPSqNSRBEDt2LLpy1Xgn6wfzeA+gpGjJZF6Qv6m77VlunuM9Vv root@r710-0201
